transform_tolerance: 0.5
obstacle_range: 50.0
raytrace_range: 60.0
map_type: costmap
robot_radius: 0.25
static_map_cost_scale: 70.0
lethal_cost_threshold: 100

static_layer:
  map_topic: /global_map
  subscribe_to_updates: true
obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: os_sensor # Your laser scan frame
    data_type: LaserScan
    topic: /nav/scan # Your laser scan topic
    marking: true
    clearing: true
    max_obstacle_height: 6.0
    min_obstacle_height: 0.0
