transform_tolerance: 0.5
obstacle_range: 50.0
raytrace_range: 60.0
map_type: costmap
robot_radius: 0.25
static_map_cost_scale: 70.0
lethal_cost_threshold: 100

static_layer:
  map_topic: /global_map
  subscribe_to_updates: true
