global_costmap:
  global_frame: robot/odom
  robot_base_frame: robot/base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: true
  resolution: 0.05
  rolling_window: false
  width: 7.0
  height: 7.0
  transform_tolerance: 1

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 5.0
