global_costmap:
  global_frame: robot/odom
  robot_base_frame: robot/base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: true
  rolling_window: false
  width: 7.0
  height: 7.0
  resolution: 0.09
  transform_tolerance: 0.5

  inflation_layer:
    inflation_radius: 0.1
    cost_scaling_factor: 3.0
