local_costmap:
  global_frame: robot/odom
  robot_base_frame: robot/base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.05
  transform_tolerance: 1

  footprint: [[0.54, 0.43], [0.54, -0.43], [-0.45, -0.43], [-0.45, 0.43]]

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  static_layer:
    map_topic: /global_map
    map_type: occupancy
    subscribe_to_updates: true
    static_map_cost_scale: 70.0
    lethal_cost_threshold: 100

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 10.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: os_sensor
      data_type: PointCloud2
      topic: /nav/obstacle_cloud
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.2
      obstacle_range: 7.0
      raytrace_range: 7.0
      observation_persistance: 0.2
