local_costmap:
  global_frame: robot/odom
  robot_base_frame: robot/base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 12.0
  height: 12.0
  resolution: 0.05
  transform_tolerance: 0.5

  inflation_layer:
    inflation_radius: 0.1
    cost_scaling_factor: 10.0
