lane_filter_node:
  higher_h: 180
  higher_s: 50
  higher_v: 255
  lower_h: 0
  lower_s: 0
  lower_v: 200
  target_v: 140

mapper_sim:
  prior: 0.5
  prob_hit: 0.8
  prob_miss: 0.2
  min_prob: 0.12
  max_prob: 0.99
  obstacle_threshold: 0.55
  resolution: 0.04
  width: 2500
  height: 2500
  preserve_meters: 10

goal_gen_node:
  explore_distance: 300
  pose_log_offset: 3
  pose_goal_offset: 5
  total_gps_goals: 4
  gps_capture_distance: 5
