controller_server:
  ros__parameters:
    controller_frequency: 30.0
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.5
      vx_min: -0.35
      vy_max: 0.5
      wz_max: 1.9
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      az_max: 3.5
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0
      regenerate_noises: false
      critics:
        ConstraintCritic:
          enabled: true
          cost_power: 1
          cost_weight: 4.0
        GoalCritic:
          enabled: true
          cost_power: 1
          cost_weight: 5.0
          threshold_to_consider: 1.4
        GoalAngleCritic:
          enabled: true
          cost_power: 1
          cost_weight: 3.0
          threshold_to_consider: 0.5
        PreferForwardCritic:
          enabled: true
          cost_power: 1
          cost_weight: 5.0
          threshold_to_consider: 0.5
        CostCritic:
          enabled: true
          cost_power: 1
          cost_weight: 3.81
          critical_cost: 300.0
          consider_footprint: true
          collision_cost: 1000000.0
          near_goal_distance: 1.0
          trajectory_point_step: 2
        PathAlignCritic:
          enabled: true
          cost_power: 1
          cost_weight: 14.0
          max_path_occupancy_ratio: 0.05
          trajectory_point_step: 4
          threshold_to_consider: 0.5
          offset_from_furthest: 20
          use_path_orientations: false
        PathFollowCritic:
          enabled: true
          cost_power: 1
          cost_weight: 5.0
          offset_from_furthest: 5
          threshold_to_consider: 1.4
        PathAngleCritic:
          enabled: true
          cost_power: 1
          cost_weight: 2.0
          offset_from_furthest: 4
          threshold_to_consider: 0.5
          max_angle_to_furthest: 1.0
          mode: 0

local_costmap:
  local_costmap:
    ros__parameters:
      qos_overrides:
        subscription:
          durability: VOLATILE
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 15
      height: 15
      resolution: 0.06
      robot_radius: 0.35
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true
        subscribe_to_updates: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: pointcloud
        pointcloud:
          topic: /lidar/points
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.9

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.5
