local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 12.0
  height: 12.0
  resolution: 0.05
  transform_tolerance: 1

  footprint:
    [
      [0.47, 0.3],
      [0.47, -0.3],
      [0.15, -0.3],
      [0.15, -0.4],
      [-0.15, -0.4],
      [-0.15, -0.3],
      [-0.40, -0.3],
      [-0.40, 0.3],
      [-0.15, 0.3],
      [-0.15, 0.4],
      [0.15, 0.4],
      [0.15, 0.3],
    ]

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

  static_layer:
    map_topic: nav/global_map
    map_type: occupancy
    subscribe_to_updates: true
    static_map_cost_scale: 70.0
    lethal_cost_threshold: 100

  inflation_layer:
    inflation_radius: 0.45
    cost_scaling_factor: 20.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: os_sensor
      data_type: PointCloud2
      topic: /nav/obstacle_cloud
      marking: true
      clearing: true
      max_obstacle_height: 2.0
      min_obstacle_height: 0.5
      obstacle_range: 5.0
      raytrace_range: 5.0
      observation_persistance: 0.2
